name: Build with Gradle

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Gradle wrapper validation
      uses: gradle/actions/wrapper-validation@v3
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Build with Gradle (CI)
      run: ./gradlew build
    - name: Run tests
      run: ./gradlew test
    - name: Create fat jar
      run: ./gradlew shadowJar

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ORIPA
        path: build/libs/*-all.jar
